include ../Make.defines

PROGS =	catgetmsg devzero mapanon mcopy \
		nonblockw pollpipe selectpipe \
		tpoll1 tselect1 tselect2 tsleepus1 \
		writev1 writev2 writev3

all:	${PROGS}

clean:
	rm -f ${PROGS} ${TEMPFILES}
