include ../Make.defines

PROGS =	abort cmd1 doatexit exitfunc getrlimit hello1 \
		mallocbug mycat mycatgo opendata.o rlimitcpu testjmp

all:	${PROGS}

clean:
	rm -f ${PROGS} ${TEMPFILES} ./foo ./bar
